name: Reporte Diario de Cripto

on:
  schedule:
    # Se ejecuta todos los días a las 14:00 UTC
    # (Equivale a las 08:00 AM en el centro de México)
    - cron: '0 00 * * *'
  workflow_dispatch: # Te permite ejecutarlo manualmente con un botón

jobs:
  ejecutar-script:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar librerías
      run: |
        pip install ccxt pandas requests

    - name: Ejecutar el script
      # Aquí le pasas variables secretas si usas un Bot de Telegram
      #env: 
        #TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        #TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python scan.py
